### ISSUE TITLE
Ignore Stores When Hot Reloading

### ISSUE THREAD

**Issue by casesandberg** [capaj/systemjs-hot-reloader#55] opened 2016-02-13 23:45 UTC
I am building out an application with Redux and it keeps throwing a warning whenever I change a component: 

```
<Provider> does not support changing `store` on the fly. 
It is most likely that you see this error because you updated to Redux 2.x 
and React Redux 2.x which no longer hot reload reducers automatically. See 
https://github.com/rackt/react-redux/releases/tag/v2.0.0 for the migration 
instructions.
```

Is there any way for it to ignore the reducer files do that they are not reloaded?

**Comment by capaj** [comment] 2016-02-13 23:49
not yet, but we were thinking about something along the lines of returning `false` from `__reload` hook with @guybedford but that will need to be verified yet.

**Comment by peteruithoven** [comment] 2016-02-14 15:09
@casesandberg You don't want to hot reload when editing reducer files? Seems like a big loss? Have you seen the following solution? 
https://github.com/capaj/systemjs-hot-reloader/issues/34#issuecomment-174723848

**Comment by alexisvincent** [comment] 2016-12-22 23:55
Closing since reloading reducers is expected behavior :)

**Closed by alexisvincent** 2016-12-22 23:55 UTC
