### ISSUE TITLE
Odd breakpoint behavior

### ISSUE THREAD

**Issue by Mosho1** [capaj/systemjs-hot-reloader#90] opened 2016-05-22 00:53 UTC
On chrome (50.0.2661.102) with v0.5.6, after hot reloading, breakpoints are dim (inactive) although they still stop execution, and I can't remove them by clicking on them. If I remove them from the breakpoints list, the line number (dimmed) markings are still there but the breakpoint doesn't stop execution. If I reload again, the breakpoints are active again (ignoring my removal of them before the reload).

Note that this doesn't happen when using [jspm-server](https://github.com/geelen/jspm-server).

**Comment by capaj** [comment] 2016-05-25 08:35
@Mosho1 I have seen this behaviour with react-hot-loader and webpack. As far as I am aware, this is either a chrome bug or working as intended-it might be some kind of limitation when debugger is working with sourcemaps. I am closing this for now, I don't think anyone outside or chrome team will be able to solve this one.

**Closed by capaj** 2016-05-25 08:35 UTC

**Comment by born2net** [comment] 2016-06-05 13:08
Anyone know where to post for Google team to take a look into this?
They are pretty responsive if we can just make them aware of the problem,
regards

Sean

**Comment by Mosho1** [comment] 2016-06-05 13:33
Maybe chromium's issue tracker?

https://bugs.chromium.org/p/chromium/issues/list

**Comment by born2net** [comment] 2016-06-05 13:47
tx posted: https://bugs.chromium.org/p/chromium/issues/detail?id=617450#
